In [9]:
import sys
import numpy as np

sys.path.append('../src')
from vel_verlet import VelocityVerlet
from elec_method.electronic_interface import ElectronicInterface
from nuc_method.nuc_interface import NuclearInterface

# Testing the potential

In [10]:
potential = ElectronicInterface('Tully1')

In [11]:
positions = np.array([-1])
energies, gradients, nacvs = potential.compute_electronic(positions, 0)

In [12]:
print(energies)
print(gradients)
print(nacvs)

[-0.00819026  0.00819026]
[[ 0.00232163]
 [-0.00232163]]
[ 0.         -0.26313592]


# Testing the dynamics method

In [13]:
mass = np.array([2000])
dynamic = NuclearInterface(mass, 'AIMS', 'Tully1')

In [14]:
dynamic.acceleration(positions, 0)

(array([-1.16081386e-06]),
 {'energies': array([-0.00819026,  0.00819026]),
  'gradients': array([[ 0.00232163],
         [-0.00232163]]),
  'nacvs': array([ 0.        , -0.26313592])})

# Testing verlet propagation

In [15]:
verlet = VelocityVerlet()

new_pos = np.array([-1])
new_vel = np.array([0.001])
new_acc = np.array([0])

for i in range(100):

    old_pos, old_vel, old_acc = new_pos, new_vel, new_acc

    new_pos, new_vel, new_acc, _ = verlet.take_step(old_pos = old_pos,
                                                    old_vel = old_vel,
                                                    old_acc = old_acc,
                                                    dt = 0.1,
                                                    acc_func = dynamic.acceleration,
                                                    state = 0)
    
    print(f'at time {i} the new position is {new_pos}')
    print(f'at time {i} the new velocity is {new_vel}')

at time 0 the new position is [-0.9999]
at time 0 the new velocity is [0.00099994]
at time 1 the new position is [-0.99980001]
at time 1 the new velocity is [0.00099983]
at time 2 the new position is [-0.99970003]
at time 2 the new velocity is [0.00099971]
at time 3 the new position is [-0.99960007]
at time 3 the new velocity is [0.00099959]
at time 4 the new position is [-0.99950012]
at time 4 the new velocity is [0.00099948]
at time 5 the new position is [-0.99940017]
at time 5 the new velocity is [0.00099936]
at time 6 the new position is [-0.99930024]
at time 6 the new velocity is [0.00099925]
at time 7 the new position is [-0.99920033]
at time 7 the new velocity is [0.00099913]
at time 8 the new position is [-0.99910042]
at time 8 the new velocity is [0.00099901]
at time 9 the new position is [-0.99900052]
at time 9 the new velocity is [0.0009989]
at time 10 the new position is [-0.99890064]
at time 10 the new velocity is [0.00099878]
at time 11 the new position is [-0.99880077]
a

In [16]:
new_pos

array([-0.99005762])

In [18]:
tmp = np.empty(shape=(2,6))
tmp[0]

array([4.64691555e-310, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       1.16709769e-312, 7.40678483e-038])